version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - config-network
    environment:
      - MONGO_INITDB_DATABASE=ConfigDB

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - config-network
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  servicea:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - mongodb
      - rabbitmq
    networks:
      - config-network
    environment:
      - MongoConnectionString=mongodb://mongodb:27017
      - MongoDatabaseName=ConfigDB
      - MongoCollectionName=Configurations
      - RabbitMQConnectionString=amqp://guest:guest@rabbitmq:5672/
      - ServiceName=SERVICE-A
      - ConfigCheckIntervalSeconds=30

  beymen.configuration.test:
    image: ${DOCKER_REGISTRY-}beymenconfigurationtest
    build:
      context: .
      dockerfile: Beymen.Configuration.Test/Dockerfile

networks:
  config-network:
    driver: bridge

