version: '3.4'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  servicea:
    build: ./ServiceA
    depends_on:
      - mongodb
    environment:
      - MongoConnectionString=mongodb://mongodb:27017

volumes:
  mongo-data: